import { useEffect, useState } from 'react'
import { MessageCircle, Trash2 } from 'lucide-react'
import { supabase } from '@/lib/supabase'
import { Card } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { useAuth } from '@/auth/AuthContext'
type RequestRow={id:number;public_id:string;request_type:'question'|'rendez_vous';full_name:string;phone:string|null;discord_username:string|null;subject:string;message:string;created_at:string}
type Msg={id:number;request_id:number;sender:'visitor'|'ems';body:string;created_at:string}
export function PatientArchiveSection(){
 const { staff } = useAuth(); const canDelete=staff?.role==='directeur'
 async function removeSelected(){if(!selected||!canDelete||!window.confirm('Supprimer définitivement ce message patient et toute la conversation ?'))return; const {error}=await supabase.from('visitor_requests').delete().eq('id',selected.id); if(error){window.alert(error.message);return} setRows(v=>v.filter(x=>x.id!==selected.id));setSelected(null);setMessages([])}
 const [rows,setRows]=useState<RequestRow[]>([]); const [selected,setSelected]=useState<RequestRow|null>(null); const [messages,setMessages]=useState<Msg[]>([])
 useEffect(()=>{supabase.from('visitor_requests').select('*').in('request_type',['question','rendez_vous']).eq('status','ferme').order('updated_at',{ascending:false}).then(({data})=>setRows((data??[]) as RequestRow[]))},[])
 useEffect(()=>{if(!selected){setMessages([]);return} supabase.from('visitor_request_messages').select('*').eq('request_id',selected.id).order('created_at').then(({data})=>setMessages((data??[]) as Msg[]))},[selected?.id])
 return <div className="grid lg:grid-cols-[340px_1fr] gap-4"><Card className="p-4"><div className="grid gap-2">{rows.map(r=><button key={r.id} onClick={()=>setSelected(r)} className="text-left rounded-xl border border-[var(--ink)]/8 p-3"><p className="font-semibold text-sm">{r.full_name}</p><p className="text-xs text-[var(--ink)]/40">{r.subject} · {new Date(r.created_at).toLocaleDateString('fr-FR')}</p></button>)}{rows.length===0&&<p className="text-sm text-center text-[var(--ink)]/35 py-8">Aucun message patient archivé.</p>}</div></Card><Card className="p-5">{!selected?<div className="min-h-80 flex flex-col items-center justify-center text-[var(--ink)]/30"><MessageCircle/><p className="mt-2 text-sm">Sélectionne une conversation</p></div>:<div><div className="flex items-center justify-between gap-3"><h3 className="font-bold">{selected.full_name}</h3>{canDelete&&<Button size="sm" variant="ghost" onClick={removeSelected}><Trash2 size={14}/> Supprimer</Button>}</div><p className="text-xs text-[var(--ink)]/40">{selected.phone||'—'} · {selected.discord_username||'Discord'}</p><div className="rounded-xl border border-[var(--ink)]/8 p-3 mt-4"><p className="font-semibold text-sm">{selected.subject}</p><p className="text-sm mt-2">{selected.message}</p></div><div className="grid gap-2 mt-4">{messages.map(m=><div key={m.id} className={m.sender==='ems'?'ml-auto max-w-[80%] rounded-xl bg-red/8 p-3':'mr-auto max-w-[80%] rounded-xl bg-[var(--ink)]/5 p-3'}><p className="text-[10px] opacity-50">{m.sender==='ems'?'EMS':selected.full_name}</p><p className="text-sm whitespace-pre-wrap">{m.body}</p></div>)}</div></div>}</Card></div>
}
